namespace Rithmic.Core;

public interface IRCallbacks {
    rapi.RCallbacks GetRCallbacks();

    IEventDispatcher<rapi.AlertInfo>                    AlertDispatcher                    { get; }
    IEventDispatcher<rapi.AggregatorInfo>               AggregatorDispatcher               { get; }
    IEventDispatcher<rapi.AskInfo>                      AskQuoteDispatcher                 { get; }
    IEventDispatcher<rapi.AuxRefDataInfo>               AuxRefDataDispatcher               { get; }
    IEventDispatcher<BestAskQuoteInfo>                  BestAskQuoteDispatcher             { get; }
    IEventDispatcher<BestBidAskQuoteInfo>               BestBidAskQuoteDispatcher          { get; }
    IEventDispatcher<BestBidQuoteInfo>                  BestBidQuoteDispatcher             { get; }
    IEventDispatcher<rapi.BidInfo>                      BidQuoteDispatcher                 { get; }
    IEventDispatcher<rapi.BinaryContractListInfo>       BinaryContractListDispatcher       { get; }
    IEventDispatcher<rapi.CloseMidPriceInfo>            CloseMidPriceDispatcher            { get; }
    IEventDispatcher<rapi.ClosePriceInfo>               ClosePriceDispatcher               { get; }
    IEventDispatcher<rapi.ClosingIndicatorInfo>         ClosingIndicatorDispatcher         { get; }
    IEventDispatcher<rapi.DboInfo>                      DboDispatcher                      { get; }
    IEventDispatcher<rapi.DboBookRebuildInfo>           DboBookRebuildDispatcher           { get; }
    IEventDispatcher<rapi.EndQuoteInfo>                 EndQuoteDispatcher                 { get; }
    IEventDispatcher<rapi.EquityOptionStrategyListInfo> EquityOptionStrategyListDispatcher { get; }
    IEventDispatcher<rapi.HighPriceInfo>                HighPriceDispatcher                { get; }
    IEventDispatcher<rapi.HighBidPriceInfo>             HighBidPriceDispatcher             { get; }
    IEventDispatcher<rapi.HighPriceLimitInfo>           HighPriceLimitDispatcher           { get; }
    IEventDispatcher<rapi.InstrumentByUnderlyingInfo>   InstrumentByUnderlyingDispatcher   { get; }
    IEventDispatcher<rapi.InstrumentSearchInfo>         InstrumentSearchDispatcher         { get; }
    IEventDispatcher<rapi.OrderBookInfo>                LimitOrderBookDispatcher           { get; }
    IEventDispatcher<rapi.LowPriceInfo>                 LowPriceDispatcher                 { get; }
    IEventDispatcher<rapi.LowAskPriceInfo>              LowAskPriceDispatcher              { get; }
    IEventDispatcher<rapi.LowPriceLimitInfo>            LowPriceLimitDispatcher            { get; }
    IEventDispatcher<rapi.MarketModeInfo>               MarketModeDispatcher               { get; }
    IEventDispatcher<rapi.MidPriceInfo>                 MidPriceDispatcher                 { get; }
    IEventDispatcher<rapi.OpenInterestInfo>             OpenInterestDispatcher             { get; }
    IEventDispatcher<rapi.OpenPriceInfo>                OpenPriceDispatcher                { get; }
    IEventDispatcher<rapi.OpeningIndicatorInfo>         OpeningIndicatorDispatcher         { get; }
    IEventDispatcher<rapi.OptionListInfo>               OptionListDispatcher               { get; }
    IEventDispatcher<rapi.PriceIncrInfo>                PriceIncrUpdateDispatcher          { get; }
    IEventDispatcher<rapi.ProjectedSettlementPriceInfo> ProjectedSettlementPriceDispatcher { get; }
    IEventDispatcher<rapi.RefDataInfo>                  RefDataDispatcher                  { get; }
    IEventDispatcher<rapi.SettlementPriceInfo>          SettlementPriceDispatcher          { get; }
    IEventDispatcher<rapi.StrategyInfo>                 StrategyDispatcher                 { get; }
    IEventDispatcher<rapi.StrategyListInfo>             StrategyListDispatcher             { get; }
    IEventDispatcher<rapi.TradeInfo>                    TradeConditionDispatcher           { get; }
    IEventDispatcher<rapi.TradeInfo>                    TradePrintDispatcher               { get; }
    IEventDispatcher<rapi.TradeVolumeInfo>              TradeVolumeDispatcher              { get; }
    IEventDispatcher<rapi.UserDefinedSpreadCreateInfo>  UserDefinedSpreadCreateDispatcher  { get; }
    IEventDispatcher<rapi.UserListInfo>                 UserListDispatcher                 { get; }
    IEventDispatcher<rapi.UserProfileInfo>              UserProfileDispatcher              { get; }
    IEventDispatcher<rapi.VolumeAtPriceInfo>            VolumeAtPriceDispatcher            { get; }
    IEventDispatcher<rapi.BarInfo>                      BarDispatcher                      { get; }
    IEventDispatcher<rapi.BarReplayInfo>                BarReplayDispatcher                { get; }
    IEventDispatcher<rapi.TradeReplayInfo>              TradeReplayDispatcher              { get; }
    IEventDispatcher<rapi.AccountListInfo>              AccountListDispatcher              { get; }
    IEventDispatcher<rapi.AccountUpdateInfo>            AccountUpdateDispatcher            { get; }
    IEventDispatcher<rapi.PasswordChangeInfo>           PasswordChangeDispatcher           { get; }
    IEventDispatcher<rapi.AutoLiquidateInfo>            AutoLiquidateDispatcher            { get; }
    IEventDispatcher<rapi.BracketReplayInfo>            BracketReplayDispatcher            { get; }
    IEventDispatcher<rapi.BracketTierModifyInfo>        BracketTierModifyDispatcher        { get; }
    IEventDispatcher<rapi.BracketInfo>                  BracketUpdateDispatcher            { get; }
    IEventDispatcher<rapi.EasyToBorrowInfo>             EasyToBorrowDispatcher             { get; }
    IEventDispatcher<rapi.EasyToBorrowListInfo>         EasyToBorrowListDispatcher         { get; }
    IEventDispatcher<rapi.ExchangeListInfo>             ExchangeListDispatcher             { get; }
    IEventDispatcher<rapi.ExecutionReplayInfo>          ExecutionReplayDispatcher          { get; }
    IEventDispatcher<rapi.IbListInfo>                   IbListDispatcher                   { get; }
    IEventDispatcher<rapi.LineInfo>                     LineUpdateDispatcher               { get; }
    IEventDispatcher<rapi.OrderReplayInfo>              OpenOrderReplayDispatcher          { get; }
    IEventDispatcher<rapi.OrderHistoryDatesInfo>        OrderHistoryDatesDispatcher        { get; }
    IEventDispatcher<rapi.OrderReplayInfo>              OrderReplayDispatcher              { get; }
    IEventDispatcher<rapi.PnlReplayInfo>                PnlReplayDispatcher                { get; }
    IEventDispatcher<rapi.PnlInfo>                      PnlUpdateDispatcher                { get; }
    IEventDispatcher<rapi.PositionExitInfo>             PositionExitDispatcher             { get; }
    IEventDispatcher<rapi.ProductRmsListInfo>           ProductRmsListDispatcher           { get; }
    IEventDispatcher<rapi.QuoteInfo>                    QuoteDispatcher                    { get; }
    IEventDispatcher<rapi.QuoteReport>                  QuoteReportDispatcher              { get; }
    IEventDispatcher<rapi.QuoteReplayInfo>              QuoteReplayDispatcher              { get; }
    IEventDispatcher<rapi.SingleOrderReplayInfo>        SingleOrderReplayDispatcher        { get; }
    IEventDispatcher<rapi.SodReport>                    SodUpdateDispatcher                { get; }
    IEventDispatcher<rapi.TradeRouteInfo>               TradeRouteDispatcher               { get; }
    IEventDispatcher<rapi.TradeRouteListInfo>           TradeRouteListDispatcher           { get; }
    IEventDispatcher<rapi.OrderBustReport>              BustReportDispatcher               { get; }
    IEventDispatcher<rapi.OrderCancelReport>            CancelReportDispatcher             { get; }
    IEventDispatcher<rapi.OrderFailureReport>           FailureReportDispatcher            { get; }
    IEventDispatcher<rapi.OrderFillReport>              FillReportDispatcher               { get; }
    IEventDispatcher<rapi.OrderModifyReport>            ModifyReportDispatcher             { get; }
    IEventDispatcher<rapi.OrderNotCancelledReport>      NotCancelledReportDispatcher       { get; }
    IEventDispatcher<rapi.OrderNotModifiedReport>       NotModifiedReportDispatcher        { get; }
    IEventDispatcher<rapi.OrderReport>                  OtherReportDispatcher              { get; }
    IEventDispatcher<rapi.OrderRejectReport>            RejectReportDispatcher             { get; }
    IEventDispatcher<rapi.OrderStatusReport>            StatusReportDispatcher             { get; }
    IEventDispatcher<rapi.OrderTradeCorrectReport>      TradeCorrectReportDispatcher       { get; }
    IEventDispatcher<rapi.OrderTriggerPulledReport>     TriggerPulledReportDispatcher      { get; }
    IEventDispatcher<rapi.OrderTriggerReport>           TriggerReportDispatcher            { get; }
    IEventDispatcher<rapi.AgreementListInfo>            AgreementListDispatcher            { get; }
}